services:
  doct_user.my_provider:
    class: Madalynn\MainBundle\Security\Provider\EMailProvider
    public: false
    arguments: ["@fos_user.user_manager"]
  twig.extension.twigext:
    class: Madalynn\MainBundle\Twig\Extension\MyExtensions
    tags:
      - { name: twig.extension }